# Generated by Django 5.2.4 on 2025-07-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('type', models.CharField(choices=[('original', 'Original'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='original', max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.content')),
            ],
        ),
    ]
