# Generated by Django 5.2.4 on 2025-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentdependency_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='conversion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
