# Generated by Django 5.2.4 on 2025-07-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_conversion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='content.content'),
        ),
    ]
